apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  creationTimestamp: null
  labels:
    kubevirt.io/vm: vm-test-14
  name: vm-test-14
  annotations:
    vm.kubevirt.io/template: fedora-desktop-small-with-rules
    vm.kubevirt.io/template-namespace: default
spec:
  running: false
  template:
    metadata:
      creationTimestamp: null
      labels:
        kubevirt.io/vm: vm-test-14
    spec:
      domain:
        cpu:
          sockets: 1
          # cores and threads should be 1 by default, so the rule should pass
        devices:
          interfaces:
            - name: default
              bridge: {}
        machine:
          type: "q35"
        resources:
          requests:
            memory: 128M
      networks:
        - name: default
          pod: {}
      evictionStrategy: LiveMigrate
      terminationGracePeriodSeconds: 0
status: {}
